#!/usr/bin/env php
<?php

$src = $argv[1];
$dstJS = "ecom/js/react-page.js";
$dstCSS = "ecom/style.css";

$orderJS = [
    "view/header/Categories.js",
    "view/header/Search.js",
    "view/header/CartIcon.js",
    "view/header/UserInfo.js",
    "view/header/Logo.js",
    "view/header/Header.js",
    "view/content/homepage/About.js",
    "view/content/homepage/Popular.js",
    "view/content/homepage/TopBanner.js",
    "view/content/homepage/Homepage.js",
    "view/content/Content.js",
    "App.js",
    "index.js"
];

$orderCSS = [
    "view/content/homepage/topbanner.css",
    "view/content/homepage/popular.css",
    "view/header/logo.css",
    "view/header/logo-tablet.css",
    "view/header/search.css",
    "view/header/search-tablet.css",
    "view/header/search-phone.css",
    "view/header/userinfo.css",
    "view/header/categories.css",
    "view/header/categories-tablet.css",
    "view/header/categories-phone.css",
    "view/header/header.css",
    "style.css"
];

$bundle = function($src, $order, $dst) {
    $bundle = [];

    foreach($order as $file) {
        $bundle[] = file_get_contents($src.$file);
    }

    file_put_contents($dst, implode("\n", $bundle));
};

$bundle($src, $orderJS, $dstJS);
$bundle($src, $orderCSS, $dstCSS);